### ISSUE TITLE
Update Gemfile.lock to solve vulnerabilities

### ISSUE THREAD

**Issue by julesinberlin** [ruby-stars/housemate#24]

**Comment by julesinberlin** [comment]
Resolved with [Updating Gemfile.lock in order to resolve vulnerabilities](://github.com/ruby-stars/housemate/pull/31)

**Comment by eva7180** [comment]
merged issue branch into master

**Comment by julesinberlin** [comment]
As the error is still being displayed after the last merge, the merge request seems to not have solved the issue.
Reopening it ;)

**Comment by eva7180** [comment]
I merged your fix again, but it is still not solved @julesinberlin 
I see that bootstrap is updated in gemfile.lock but not in actual gemfile:
![image](https://user-images.githubusercontent.com/25183540/45919163-b4f09080-be91-11e8-8041-ef05a03566cb.png)

**Comment by julesinberlin** [comment]
here you go ;) : https://github.com/ruby-stars/housemate/pull/34
