### ISSUE TITLE
calendar view for selecting Task duedate

### ISSUE THREAD

**Issue by eva7180** [ruby-stars/housemate#37]
- currently this is a normal date_select (day month year)
- should be a pop-up calendar instead

Example:
![image](https://user-images.githubusercontent.com/25183540/45933481-f1a1b200-bf8d-11e8-89e8-eafc8f316122.png)

**Comment by eva7180** [comment]
solved in branch _datepicker_ : added gem _bootstrap-datepicker-rails_ [https://github.com/Nerian/bootstrap-datepicker-rails](url)

**Comment by eva7180** [comment]
#42

**Comment by julesinberlin** [comment]
solved with merge of https://github.com/ruby-stars/housemate/pull/42
